name: Linux CI

on: [push, pull_request]

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest

    env:
      # Needed for Poetry in a private repo
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python Dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get install cmake build-essential pkg-config libpython3-dev python3-numpy libboost-all-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Poetry
        run: sudo pip3 install -U pip poetry

      - name: Install Project
        run: |
          poetry install
          poetry run pip install -U torch gpytorch

      - name: Run Tests
        run: poetry run pytest
